apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yml

namespace: collector-prod

images:
- name: collector-catalog-service
  newName: ghcr.io/acestv/collector/collector-catalog-service
  newTag: cb527e434224a4058caf952112623ee75c6add8f
- name: collector-chat-service
  newName: ghcr.io/acestv/collector/collector-chat-service
  newTag: cb527e434224a4058caf952112623ee75c6add8f
- name: collector-fraud-service
  newName: ghcr.io/acestv/collector/collector-fraud-service
  newTag: cb527e434224a4058caf952112623ee75c6add8f
- name: collector-frontend
  newName: ghcr.io/acestv/collector/collector-frontend
  newTag: cb527e434224a4058caf952112623ee75c6add8f
- name: collector-gateway
  newName: ghcr.io/acestv/collector/collector-gateway
  newTag: cb527e434224a4058caf952112623ee75c6add8f
- name: collector-keycloak
  newName: ghcr.io/acestv/collector/collector-keycloak
  newTag: main
- name: collector-notification-service
  newName: ghcr.io/acestv/collector/collector-notification-service
  newTag: cb527e434224a4058caf952112623ee75c6add8f
- name: collector-order-service
  newName: ghcr.io/acestv/collector/collector-order-service
  newTag: cb527e434224a4058caf952112623ee75c6add8f
- name: collector-payment-service
  newName: ghcr.io/acestv/collector/collector-payment-service
  newTag: cb527e434224a4058caf952112623ee75c6add8f
- name: collector-user-service
  newName: ghcr.io/acestv/collector/collector-user-service
  newTag: cb527e434224a4058caf952112623ee75c6add8f

# No ingress host patch needed if base uses collector.local, or we can patch it explicitly
patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: collector.local
  target:
    kind: Ingress
    name: collector-ingress
